### ISSUE TITLE
アプリケーションをデプロイする。

### ISSUE THREAD

**Issue by arata-t** [arata-t/coffee-app#25]
## 概要
herokuではアプリ直下にpackage.jsonがないといけないので、デプロイができない。
この問題を解決するために、以下の手段をとる。

1. 開発ブランチで、デプロイできるかを試す。
2. buildしたから自動でルートディレクトリにpackage.jsonが上書きされるように設定する。

## ブランチ
25/deploy-parent

## issue

- [x] #26
- [x] #27
- [x] #28
- [x] 特定のブランチをherokuにpushする
- [x] #30
- [x] #32

**Comment by arata-t** [comment]
## 特定のブランチをherokuにpushする

`git push heroku 25/deploy-parent:main`でいける？
=> いけた！！

**Comment by arata-t** [comment]
## migrateのエラー
<details>
heroku run rails db:migrate
Running rails db:migrate on ⬢ coffee-app-20230304... up, run.6312 (Basic)
rails aborted!
Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/app/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.4/lib/mysql2/client.rb:95:in `connect'
/app/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.4/lib/mysql2/client.rb:95:in `initialize'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/connection_handling.rb:189:in `connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/railties/databases.rake:84:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.5/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.5/lib/rails/command.rb:48:in `invoke'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.5/lib/rails/commands.rb:18:in `<main>'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/bin/rails:9:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
</details>

## 対処
herokuのDBへの設定が行われていなかったのが、原因
```
% heroku_cleardb=`heroku config:get CLEARDB_DATABASE_URL`
% heroku config:set DATABASE_URL=mysql2${heroku_cleardb:5}
```
以上を追加することで解決した、。

**Comment by arata-t** [comment]
## Mixed Contentエラー

デプロイ後にherokuを開いたら、Mixed Contentエラーとなっており、サーバーが起動しない。
新たにissueを立てる。

**Comment by arata-t** [comment]
まだダメなようだ。
そもそも、baseURLがhttpになっているから？？
```
export default () => {
  return axios.create({
    baseURL: 'http://0.0.0.0:3000/v1'
  })
}
```

ここは変えられない

**Comment by arata-t** [comment]
## 完成
#32 でherokuへのデプロイが完了した。
しかし、herokuでDynoを登録すると、お金がかかるためOFFにしている。
現状はhttp://coffee-app-20230304.herokuapp.com/ にアクセスしても登録も参照もできない。
